/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.1.502 */
/* Module Version: 5.7 */
/* Wed Aug 31 17:51:40 2016 */

/* parameterized module instance */
vga_pll __ (.CLKI( ), .CLKOP( ));
